### PR TITLE
Auth Err - Internal Codes

### PR DESCRIPTION
**Pull request by mattevans**
Authentication errors now handle `code` passed and return within `Err.AdditionalFields` map.

**Context:**

Frontend needs a way to distinguish between authentication errors (eg: expired, invalid, malformed tokens), while still parsing/handling the `401` status code first.

**Example:**

```
ErrNoIcecream = fail.NewAuthError(422001, "No Icecream Available", noIcecreamDescription)
```

```
401 Unauthorized
{
  "error": "No Icecream Available",
  "description": "It seems all icecream has melted. This is not good. Please check your local Mr Whippey and try again.",
  "fields": {
    "internal_error_code": "422001"
  }
}
```

### CODE REVIEW

**Comment by snikch** [comment]
How does this distinguish between the internal code and the http status code?

**Comment by snikch** [comment]
So, I originally had this functionality and never used it, so ripped it out. Nice to see that my initial thoughts did have some grounding in reality!

Because these codes may actually be exposed via an api as additional information for consumers, I'm not sure `internal_error_code` is the correct field name. Perhaps just `error_code` or even `code` is sufficient.

**Comment by mattevans** [comment]
Thanks mate.

**Comment by snikch** [comment]
Also note: https://github.com/snikch/api/blob/71f6d45d2cc872a1c8e1a7c40861d858e34003fd/vc/error.go#L43

The `code` value DOES get marshalled into the output, so perhaps we could add a new field to `fail.Error` for `ErrorCode` rather than `StatusCode` which can be marshalled directly onto the root of the response rather than the fields output. Might be over engineering. I'll leave this one with you.

**Pull request merged**
